import React from 'react';
import {
  Bell,
  BellRing,
  Bot,
  Calendar,
  ChartColumn,
  CircleCheck,
  ClipboardPaste,
  Clock,
  Copy,
  Database,
  Download,
  FileSpreadsheet,
  FileText,
  Filter,
  Hourglass,
  Inbox,
  IndianRupee,
  Keyboard,
  ListChecks,
  Mail,
  MessageCircle,
  MousePointerClick,
  Package,
  Paperclip,
  Phone,
  Receipt,
  RefreshCw,
  Repeat,
  ScanBarcode,
  Search,
  Send,
  ShoppingCart,
  Sparkles,
  Star,
  Table,
  Tag,
  Timer,
  TriangleAlert,
  Truck,
  User,
  Users,
  Waves,
  Workflow,
  Zap,
} from 'lucide-react';
import names from './icon-names.json';

const COMPONENTS: Record<string, React.ComponentType<{size?: number; color?: string; strokeWidth?: number}>> = {
  Bell,
  BellRing,
  Bot,
  Calendar,
  ChartColumn,
  CircleCheck,
  ClipboardPaste,
  Clock,
  Copy,
  Database,
  Download,
  FileSpreadsheet,
  FileText,
  Filter,
  Hourglass,
  Inbox,
  IndianRupee,
  Keyboard,
  ListChecks,
  Mail,
  MessageCircle,
  MousePointerClick,
  Package,
  Paperclip,
  Phone,
  Receipt,
  RefreshCw,
  Repeat,
  ScanBarcode,
  Search,
  Send,
  ShoppingCart,
  Sparkles,
  Star,
  Table,
  Tag,
  Timer,
  TriangleAlert,
  Truck,
  User,
  Users,
  Waves,
  Workflow,
  Zap,
};

export const Icon: React.FC<{name?: string; size?: number; color?: string; stroke?: number}> = ({
  name,
  size = 32,
  color = 'currentColor',
  stroke = 2.2,
}) => {
  const key = (name || 'sparkles').toLowerCase();
  const compName = (names as Record<string, string>)[key] ?? 'Sparkles';
  const Comp = COMPONENTS[compName] ?? Sparkles;
  return <Comp size={size} color={color} strokeWidth={stroke} />;
};
